# Generated by Django 6.0.5 on 2026-05-26 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0015_remove_engravingmockup_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipBottleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='vip/models/')),
                ('description', models.CharField(max_length=255)),
                ('icon_class', models.CharField(default='bi bi-star', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_models', to='products.product')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
