# Generated by Django 6.0.5 on 2026-05-29 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0001_initial'),
        ('products', '0015_remove_engravingmockup_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGravacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('icone', models.ImageField(upload_to='vip/categorias/')),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoria de gravação',
                'verbose_name_plural': 'Categorias de gravação',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='vipbottlemodel',
            options={},
        ),
        migrations.RenameField(
            model_name='vipbottlemodel',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='vipbottlemodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vipbottlemodel',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='vipbottlemodel',
            name='order',
        ),
        migrations.AlterField(
            model_name='vipbottlemodel',
            name='image',
            field=models.ImageField(upload_to='vip/bottle_models/'),
        ),
        migrations.AlterField(
            model_name='vipbottlemodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_bottle_models', to='products.product'),
        ),
        migrations.CreateModel(
            name='Gravacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=80)),
                ('imagem', models.ImageField(upload_to='vip/gravacoes/')),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gravacoes', to='customization.categoriagravacao')),
            ],
            options={
                'verbose_name': 'Gravação',
                'verbose_name_plural': 'Gravações',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
