# Generated by Django 6.0.5 on 2026-10-08 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "customization",
            "0002_categoriagravacao_alter_vipbottlemodel_options_and_more",
        ),
        ("products", "0030_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="BottleCustomization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=15)),
                ("font", models.CharField(blank=True, max_length=100)),
                ("configuration", models.JSONField(default=dict)),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="customizations/previews/"
                    ),
                ),
                (
                    "texture_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="customizations/textures/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bottle_customizations",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Personalização de garrafa",
                "verbose_name_plural": "Personalizações de garrafas",
                "ordering": ["-created_at"],
            },
        ),
    ]
