# Generated by Django 6.0.5 on 2026-06-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communityreview',
            old_name='text',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='communityreview',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='communityreview',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 estrela'), (2, '2 estrelas'), (3, '3 estrelas'), (4, '4 estrelas'), (5, '5 estrelas')], default=5),
        ),
        migrations.AlterField(
            model_name='communityreview',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
