# Generated by Django 6.0.5 on 2026-06-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_text_communityreview_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('coupon_code', models.CharField(default='RISK15', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email da newsletter',
                'verbose_name_plural': 'Emails da newsletter',
            },
        ),
    ]
