# Generated by Django 6.0.5 on 2026-06-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_engraving_side_orderitem_name_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='infinitepay_link',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
