# Generated by Django 6.0.5 on 2026-05-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productsize_product_productsize_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='installments',
        ),
        migrations.AddField(
            model_name='product',
            name='default_color_hex',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='default_color_name',
            field=models.CharField(default='Preto', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='image_hover',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
