# Generated by Django 6.0.5 on 2026-05-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_installments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='Produto VIP'),
        ),
    ]
