# Generated by Django 6.0.5 on 2026-05-25 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_is_vip'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngravingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoria de gravação',
                'verbose_name_plural': 'Categorias de gravação',
            },
        ),
        migrations.CreateModel(
            name='EngravingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='engravings/')),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.engravingcategory')),
            ],
            options={
                'verbose_name': 'Opção de gravação',
                'verbose_name_plural': 'Opções de gravação',
            },
        ),
    ]
