# Generated by Django 6.0.5 on 2026-05-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_engravingcategory_engravingoption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engravingoption',
            options={},
        ),
        migrations.AddField(
            model_name='engravingoption',
            name='mockup',
            field=models.ImageField(default=2, upload_to='engraving_mockups/'),
            preserve_default=False,
        ),
    ]
