# Generated by Django 6.0.5 on 2026-05-25 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_engravingoption_options_engravingoption_mockup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engravingcategory',
            options={'ordering': ['name'], 'verbose_name': 'Categoria de gravação', 'verbose_name_plural': 'Categorias de gravação'},
        ),
        migrations.AlterModelOptions(
            name='engravingoption',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Opção de gravação', 'verbose_name_plural': 'Opções de gravação'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='engravingoption',
            name='mockup',
        ),
        migrations.AddField(
            model_name='engravingcategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='EngravingMockup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='engraving_mockups/')),
                ('active', models.BooleanField(default=True)),
                ('engraving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mockups', to='products.engravingoption')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engraving_mockups', to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engraving_mockups', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Mockup de gravação',
                'verbose_name_plural': 'Mockups de gravação',
                'ordering': ['product', 'variant', 'engraving'],
            },
        ),
    ]
