# Generated by Django 6.0.5 on 2026-05-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_engravingcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engravingoption',
            name='category',
        ),
        migrations.RemoveField(
            model_name='engravingmockup',
            name='engraving',
        ),
        migrations.AlterModelOptions(
            name='engravingmockup',
            options={'ordering': ['product', 'variant', 'name'], 'verbose_name': 'Mockup de gravação', 'verbose_name_plural': 'Mockups de gravação'},
        ),
        migrations.AddField(
            model_name='engravingmockup',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EngravingCategory',
        ),
        migrations.DeleteModel(
            name='EngravingOption',
        ),
    ]
