# Generated by Django 6.0.5 on 2026-05-26 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_engravingoption_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engravingmockup',
            options={},
        ),
        migrations.CreateModel(
            name='EngravingMockupImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='engraving_mockups/gallery/')),
                ('alt', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('mockup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.engravingmockup')),
            ],
            options={
                'verbose_name': 'Imagem extra do mockup',
                'verbose_name_plural': 'Imagens extras do mockup',
            },
        ),
    ]
