# Generated by Django 6.0.5 on 2026-05-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_engravingmockup_options_engravingmockupimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engravingmockup',
            name='image',
        ),
        migrations.AddField(
            model_name='engravingmockup',
            name='main_image',
            field=models.ImageField(default=1, upload_to='engraving_mockups/main/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engravingmockup',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='engraving_mockups/thumbs/'),
            preserve_default=False,
        ),
    ]
