# Generated by Django 6.0.5 on 2026-05-31 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_engravingmockup_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='community/')),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CommunityImage',
        ),
    ]
