# Generated by Django 6.0.5 on 2026-05-31 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_communityreview_delete_communityimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityReview',
        ),
    ]
