# Generated by Django 6.0.5 on 2026-06-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_delete_communityreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagem do verso'),
        ),
    ]
