# Generated by Django 6.0.5 on 2026-06-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_back_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='back_image',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('termicas', 'Térmicas'), ('squeeze', 'Squeeze'), ('personalizadas', 'Personalizadas')], default='termicas', max_length=30),
        ),
    ]
