# Generated by Django 6.0.5 on 2026-06-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_vipproduct_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engravingmockup',
            name='product',
        ),
        migrations.RemoveField(
            model_name='engravingmockup',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='engravingmockupimage',
            name='mockup',
        ),
        migrations.DeleteModel(
            name='VipProduct',
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Imagem do produto', 'verbose_name_plural': 'Imagens do produto'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ['id'], 'verbose_name': 'Tamanho', 'verbose_name_plural': 'Tamanhos'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['id'], 'verbose_name': 'Variação de cor', 'verbose_name_plural': 'Variações de cor'},
        ),
        migrations.AlterModelOptions(
            name='variantimage',
            options={'verbose_name': 'Imagem da variação', 'verbose_name_plural': 'Imagens da variação'},
        ),
        migrations.AddField(
            model_name='variantimage',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variantimage',
            name='alt',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.DeleteModel(
            name='EngravingMockup',
        ),
        migrations.DeleteModel(
            name='EngravingMockupImage',
        ),
    ]
