# Generated by Django 6.0.5 on 2026-06-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_engravingmockup_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='engraving_position',
            field=models.CharField(
                choices=[
                    ('front', 'Frente'),
                    ('back', 'Costas'),
                    ('front_back', 'Frente e costas')
                ],
                default='front',
                max_length=20,
                verbose_name='Opções de gravação'
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(
                upload_to='products/',
                verbose_name='Imagem da frente'
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_hover',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='products/',
                verbose_name='Imagem hover'
            ),
        ),
    ]