# Generated by Django 6.0.5 on 2026-06-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_back_image_product_engraving_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/back/', verbose_name='Imagem das costas / verso'),
        ),
        migrations.AlterField(
            model_name='product',
            name='engraving_position',
            field=models.CharField(choices=[('none', 'Nenhuma gravação'), ('front', 'Frente'), ('back', 'Costas'), ('front_back', 'Frente e costas')], default='front', max_length=20, verbose_name='Opções de gravação'),
        ),
    ]
