# Generated by Django 6.0.5 on 2026-06-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_product_back_image_alter_product_engraving_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/variants/back/', verbose_name='Imagem das costas'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(upload_to='products/variants/', verbose_name='Imagem da frente'),
        ),
    ]
