# Generated by Django 6.0.5 on 2026-06-21 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_remove_product_category_productvariant_back_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDefaultSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.product')),
            ],
            options={
                'verbose_name': 'Tamanho padrão',
                'verbose_name_plural': 'Tamanhos padrão',
                'ordering': ['id'],
            },
        ),
    ]
