# Generated by Django 6.0.5 on 2026-06-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_productdefaultsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image_hover',
            field=models.ImageField(blank=True, null=True, upload_to='products/variants/hover/', verbose_name='Imagem hover'),
        ),
    ]
