# Generated by Django 6.0.5 on 2026-06-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Favorito', 'verbose_name_plural': 'Favoritos'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_createbottle',
            field=models.BooleanField(default=False, verbose_name='Disponível no CreateBottle'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_3d',
            field=models.FileField(blank=True, null=True, upload_to='products/3d/', verbose_name='Modelo 3D da garrafa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Disponível'),
        ),
        migrations.AlterField(
            model_name='productdefaultsize',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='variantimage',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
    ]
