# Generated by Django 6.0.5 on 2026-06-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_favorite_options_product_is_createbottle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model_3d',
        ),
        migrations.AddField(
            model_name='product',
            name='model_3d_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL do modelo 3D da garrafa'),
        ),
    ]
