# Generated by Django 6.0.5 on 2026-09-14 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_category'),
        ('products', '0029_remove_product_model_3d_product_model_3d_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='pages.category', verbose_name='Categoria'),
        ),
    ]
