# Generated by Django 6.0.5 on 2026-10-09 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0030_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreateBottleColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nome da cor")),
                (
                    "hex_code",
                    models.CharField(
                        default="#000000",
                        max_length=7,
                        verbose_name="Código hexadecimal",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, verbose_name="Ativa no CreateBottle"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="createbottle_colors",
                        to="products.product",
                        verbose_name="Produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cor do CreateBottle",
                "verbose_name_plural": "Cores do CreateBottle",
                "ordering": ["id"],
            },
        ),
    ]
